---
# Use container-based infrastructure
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

cache: pip

install:
  - pip install coverage==3.7
  - pip install coveralls

script:
  - coverage run --source=src setup.py test

after_success:
  - coveralls

